server:
  #服务端口号
  port: 8082

spring:
  application:
    #服务名称（服务之间通过名称通信）
    name: server-object-a
  boot:
    admin:
      client:
        url: http://localhost:9001

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    service-url:
      #eureka服务地址8081
      defaultZone: http://localhost:8080/eureka
      #将自己注册到注册中心
      register-with-eureka: true
      #搜索注册服务
      fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}