server:
  port: 9100
spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      #eureka服务地址8081
      defaultZone: http://localhost:8080/eureka
      #将自己注册到注册中心
      register-with-eureka: true
      #搜索注册服务
      fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
zuul:
  routes:
    # 三种路由配置
    server-object-a:
      path: /server-object-a/**
      serviceId: server-object-a
    server-object-b: /server-object-b/**
    server-object-c:
    