server:
  port: 9009

spring:
  application:
    name: admin-ue

eureka:
  client:
    service-url:
      #eureka\u670D\u52A1\u5730\u57408081
      defaultZone: http://localhost:8080/eureka
      #\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3
      register-with-eureka: true
      #\u641C\u7D22\u6CE8\u518C\u670D\u52A1
      fetch-registry: true
  instance:
    # \u4F7F\u7528ip\u5730\u5740\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3
    prefer-ip-address: true
    # \u6CE8\u518C\u4E2D\u5FC3\u5217\u8868\u4E2D\u663E\u793A\u7684\u72B6\u6001\u53C2\u6570
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
