server:
  port: 9009

spring:
  application:
    name: admin-ue

eureka:
  client:
    service-url:
      #eureka服务地址
      defaultZone: http://localhost:8080/eureka
      #将自己注册到注册中心
      register-with-eureka: true
      #搜索注册服务
      fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}